[package]
name = "spire-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { workspace = true }
anyhow = { workspace = true }
clap = { version = "4.5.8", features = ["derive"] }
spire-sdk = { path = "../spire-sdk" }
