[workspace]
members = [
  "spire-sdk",
  "spire-cli"
]
resolver = "2"

[workspace.package]
authors = ["Braqzen"]
edition = "2021"
license = "Apache-2.0"
version = "0.1.0"

[workspace.dependencies]
alloy = "0.2.0"
anyhow = "1.0.86"
