[package]
name = "spire-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { workspace = true }
anyhow = { workspace = true }
ethabi = "18.0.0"
rocksdb = "0.22.0"
secp256k1 = { version = "0.29.0", features = ["recovery"] }
tiny-keccak = "2.0.2"
